#define YUpHeld(x)     (x & (1 << 12))
#define YDownHeld(x)   (x & (1 << 14))
#define YLeftHeld(x)   (x & (1 << 15))
#define YRightHeld(x)  (x & (1 << 13))
#define YUpPress(x)    ((x & (1 << 12)) && (!(x & (1 << 28))))
#define YDownPress(x)  ((x & (1 << 14)) && (!(x & (1 << 30))))
#define YLeftPress(x)  ((x & (1 << 15)) && (!(x & (1 << 31))))
#define YRightPress(x) ((x & (1 << 13)) && (!(x & (1 << 29))))

#define YTriangleHeld(x)  (x & (1 << 4))
#define YXHeld(x)         (x & (1 << 6))
#define YSquareHeld(x)    (x & (1 << 7))
#define YCircleHeld(x)    (x & (1 << 5))
#define YTriaglePress(x)  ((x & (1 << 4)) && (!(x & (1 << 20))))
#define YXPress(x)        ((x & (1 << 6)) && (!(x & (1 << 22))))
#define YSquarePress(x)   ((x & (1 << 7)) && (!(x & (1 << 23))))
#define YCirclePress(x)   ((x & (1 << 5)) && (!(x & (1 << 21))))

#define YL1Held(x)        (x & (1 << 1))
#define YL2Held(x)        (x & (1 << 0))
#define YR1Held(x)        (x & (1 << 3))
#define YR2Held(x)        (x & (1 << 2))
#define YL1Press(x)       ((x & (1 << 1)) && (!(x & (1 << 17))))
#define YL2Press(x)       ((x & (1 << 0)) && (!(x & (1 << 16))))
#define YR1Press(x)       ((x & (1 << 3)) && (!(x & (1 << 19))))
#define YR2Press(x)       ((x & (1 << 2)) && (!(x & (1 << 18))))

#define YSelectHeld(x)    (x & (1 << 8))
#define YStartHeld(x)     (x & (1 << 11))
#define YSelectPress(x)   ((x & (1 << 8)) && (!(x & (1 << 24))))
#define YStartPress(x)    ((x & (1 << 11)) && (!(x & (1 << 27))))

